### ISSUE TITLE
[Android] Crash-like Behavior on Second Application Launch

### ISSUE THREAD

**Issue by RF103T** [learntoflutter/flutter_embed_unity#39]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Unity version

- [x] I am using Unity 2022.3 LTS

### Common issues

- [x] I have checked the common issues

### Flutter version

3.27.1

#### Test in all of the following Unity versions:
* 2022.3.33f1c1
* 2022.3.60f1

#### Steps:
1. Use the example project to build and install on the phone.
2. Wait for Unity to enter the first scene.
3. Return to home screen using back gesture. 
4. Open the example application again.
5. After a brief freeze, the example application exits completely. It looks like it's crashing.

I think it might be because Unity kills the entire app after detecting that the Flutter activity has been destroyed upon the second launch of the application. 

### Minimum reproducible example (MRE)

Build android apk with the example project.

### What platforms are you seeing the problem on?

Android

### Devices

* #### [NIO Phone 2](https://www.gsmarena.com/_nio_phone_2-13238.php)
> It's the very niche phone, but its OS (SkyUI) is almost identical to native Android 14. So I think there should be more devices with similar problems.
* #### HUAWEI Pura 70

### Anything else?

<details>
<summary>Log when using back gesture to return to home screen</summary>

```
0001/01/01` 00:00:00.000 -1 -1 Info  --------- beginning of main
2025/03/22 17:51:35.364 15630 15630 Info Activity onBackPressed in com.learntoflutter.flutter_embed_unity_android_example.MainActivity
2025/03/22 17:51:35.382 15630 15630 Debug perfmonitor paused={com.learntoflutter.flutter_embed_unity_android_example/com.learntoflutter.flutter_embed_unity_android_example.MainActivity} state=3
2025/03/22 17:51:35.972 15630 15630 Debug FlutterEmbedLog UnityPlayerCustom onFlutterViewDetached
2025/03/22 17:51:35.972 15630 15697 Error BufferQueueProducer [ImageReader-1440x2015f22m5-15630-0](id:3d0e00000002,api:1,p:1815,c:15630) dequeueBuffer: BufferQueue has been abandoned
2025/03/22 17:51:35.978 15630 15690 Info native I0000 00:00:1742637095.978034   15690 arpresto_api.cc:212] ArPresto::ArPresto_setEnabled
2025/03/22 17:51:35.978 15630 15690 Info native I0000 00:00:1742637095.978132   15690 arpresto_api.cc:278] ArPresto::ArPresto_reset
2025/03/22 17:51:35.978 15630 15690 Info native I0000 00:00:1742637095.978139   15690 arpresto_api.cc:193] ArPresto::ArPresto_setCameraTextureNames
2025/03/22 17:51:36.012 15630 15690 Debug android_example PlayerBase::stop() from IPlayer
2025/03/22 17:51:36.012 15630 15690 Debug AudioTrack stop(135): prior state:STATE_ACTIVE output 13 stream 3 session 1305
2025/03/22 17:51:36.012 15630 15690 Debug AudioTrack stop(135): called with 663360 frames delivered
2025/03/22 17:51:36.023 15630 15690 Debug AudioTrack stop(135): prior state:STATE_STOPPED output 13 stream 3 session 1305
2025/03/22 17:51:36.023 15630 15690 Debug AudioTrack ~AudioTrack, releasing mStatus =0 session id 1305 from 15630
2025/03/22 17:51:36.024 15630 15690 Debug AudioTrack stop(135): prior state:STATE_STOPPED output 13 stream 3 session 1305
2025/03/22 17:51:36.034 15630 15690 Debug Unity Input System module state changed to: ShutdownInProgress.
2025/03/22 17:51:36.034 15630 15690 Debug Unity Input System polling thread exited.
2025/03/22 17:51:36.034 15630 15690 Debug Unity Input System module state changed to: Shutdown.
2025/03/22 17:51:36.047 15630 15690 Debug Unity PlayerConnection::Cleanup
2025/03/22 17:51:36.060 15630 15690 Error Unity JNI:~AssetPackManager:java.lang.IllegalArgumentException: Null parameter detected
2025/03/22 17:51:36.067 15630 15690 Debug Unity Memory Statistics:
2025/03/22 17:51:36.067 15630 15690 Debug Unity [ALLOC_TEMP_TLS] TLS Allocator
2025/03/22 17:51:36.067 15630 15690 Debug Unity   StackAllocators : 
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_MAIN_THREAD]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak usage frame count: 
2025/03/22 17:51:36.067 15630 15690 Debug Unity [4.0 KB-8.0 KB]: 309 frames
2025/03/22 17:51:36.067 15630 15690 Debug Unity , [2.0 MB-4.0 MB]: 1 frames
2025/03/22 17:51:36.067 15630 15690 Debug Unity 
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 4.0 MB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 4.0 MB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 2.1 MB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Background Job.Worker 8]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Background Job.Worker 10]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Job.Worker 4]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 256.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 256.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Background Job.Worker 6]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_AUDIO_FMOD mixer thread]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 64.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 64.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Background Job.Worker 1]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Background Job.Worker 11]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Background Job.Worker 3]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_BatchDeleteObjects]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 64.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 64.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_AUDIO_FMOD stream thread]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 64.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 64.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Background Job.Worker 2]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Background Job.Worker 7]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Background Job.Worker 15]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Job.Worker 1]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 256.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 256.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 199 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Loading.PreloadManager]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 256.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 256.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 130.3 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 5
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Profiler.Dispatcher]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 64.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 64.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 456 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Job.Worker 3]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 256.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 256.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Background Job.Worker 12]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_AssetGarbageCollectorHelper] x 6
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 64.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 64.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 28 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Background Job.Worker 5]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Background Job.Worker 13]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Job.Worker 2]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 256.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 256.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Background Job.Worker 0]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Background Job.Worker 4]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 32.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Job.Worker 0]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 256.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Current Block Size 256.0 KB
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.067 15630 15690 Debug Unity     [ALLOC_TEMP_Job.Worker 5]
2025/03/22 17:51:36.067 15630 15690 Debug Unity       Initial Block Size 256.0 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Current Block Size 256.0 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_TEMP_Background Job.Worker 14]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Initial Block Size 32.0 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Current Block Size 32.0 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_TEMP_Background Job.Worker 9]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Initial Block Size 32.0 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Current Block Size 32.0 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_TEMP_EnlightenWorker]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Initial Block Size 64.0 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Current Block Size 64.0 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated Bytes 0 B
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_TEMP_UnityGfxDeviceWorker]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Initial Block Size 256.0 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Current Block Size 256.0 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated Bytes 28.8 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_TEMP_Loading.AsyncRead]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Initial Block Size 64.0 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Current Block Size 128.0 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated Bytes 126.9 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Overflow Count 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity [ALLOC_MEMORYPROFILER]
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Peak usage frame count: 
2025/03/22 17:51:36.068 15630 15690 Debug Unity [64.0 KB-128.0 KB]: 310 frames
2025/03/22 17:51:36.068 15630 15690 Debug Unity 
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Requested Block Size 1.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Peak Block count 1
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Peak Allocated memory 103.6 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Peak Large allocation bytes 0 B
2025/03/22 17:51:36.068 15630 15690 Debug Unity [ALLOC_DEFAULT] Dual Thread Allocator
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Peak main deferred allocation count 25
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_BUCKET]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Large Block size 4.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Used Block count 1
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated bytes 0.9 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_DEFAULT_MAIN]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak usage frame count: 
2025/03/22 17:51:36.068 15630 15690 Debug Unity [32.0 MB-64.0 MB]: 310 frames
2025/03/22 17:51:36.068 15630 15690 Debug Unity 
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Requested Block Size 16.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Block count 3
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated memory 44.3 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Large allocation bytes 8.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_DEFAULT_THREAD]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak usage frame count: 
2025/03/22 17:51:36.068 15630 15690 Debug Unity [16.0 MB-32.0 MB]: 310 frames
2025/03/22 17:51:36.068 15630 15690 Debug Unity 
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Requested Block Size 16.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Block count 1
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated memory 18.1 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Large allocation bytes 16.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity [ALLOC_TEMP_JOB_1_FRAME]
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Initial Block Size 2.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Used Block Count 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Overflow Count (too large) 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Overflow Count (full) 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity [ALLOC_TEMP_JOB_2_FRAMES]
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Initial Block Size 2.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Used Block Count 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Overflow Count (too large) 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Overflow Count (full) 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity [ALLOC_TEMP_JOB_4_FRAMES (JobTemp)]
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Initial Block Size 2.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Used Block Count 1
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Overflow Count (too large) 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Overflow Count (full) 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity [ALLOC_TEMP_JOB_ASYNC (Background)]
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Initial Block Size 1.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Used Block Count 1
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Overflow Count (too large) 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Overflow Count (full) 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity [ALLOC_GFX] Dual Thread Allocator
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Peak main deferred allocation count 8
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_BUCKET]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Large Block size 4.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Used Block count 1
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated bytes 0.9 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_GFX_MAIN]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak usage frame count: 
2025/03/22 17:51:36.068 15630 15690 Debug Unity [32.0 KB-64.0 KB]: 309 frames
2025/03/22 17:51:36.068 15630 15690 Debug Unity , [64.0 KB-128.0 KB]: 1 frames
2025/03/22 17:51:36.068 15630 15690 Debug Unity 
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Requested Block Size 16.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Block count 1
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated memory 67.1 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Large allocation bytes 0 B
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_GFX_THREAD]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak usage frame count: 
2025/03/22 17:51:36.068 15630 15690 Debug Unity [4.0 KB-8.0 KB]: 309 frames
2025/03/22 17:51:36.068 15630 15690 Debug Unity , [8.0 KB-16.0 KB]: 1 frames
2025/03/22 17:51:36.068 15630 15690 Debug Unity 
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Requested Block Size 16.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Block count 1
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated memory 9.1 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Large allocation bytes 0 B
2025/03/22 17:51:36.068 15630 15690 Debug Unity [ALLOC_CACHEOBJECTS] Dual Thread Allocator
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Peak main deferred allocation count 1
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_BUCKET]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Large Block size 4.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Used Block count 1
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated bytes 0.9 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_CACHEOBJECTS_MAIN]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak usage frame count: 
2025/03/22 17:51:36.068 15630 15690 Debug Unity [4.0 MB-8.0 MB]: 309 frames
2025/03/22 17:51:36.068 15630 15690 Debug Unity , [8.0 MB-16.0 MB]: 1 frames
2025/03/22 17:51:36.068 15630 15690 Debug Unity 
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Requested Block Size 4.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Block count 3
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated memory 8.8 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Large allocation bytes 0 B
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_CACHEOBJECTS_THREAD]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak usage frame count: 
2025/03/22 17:51:36.068 15630 15690 Debug Unity [4.0 MB-8.0 MB]: 309 frames
2025/03/22 17:51:36.068 15630 15690 Debug Unity , [8.0 MB-16.0 MB]: 1 frames
2025/03/22 17:51:36.068 15630 15690 Debug Unity 
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Requested Block Size 4.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Block count 2
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated memory 8.8 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Large allocation bytes 3.8 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity [ALLOC_TYPETREE] Dual Thread Allocator
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Peak main deferred allocation count 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_BUCKET]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Large Block size 4.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Used Block count 1
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated bytes 0.9 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_TYPETREE_MAIN]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak usage frame count: 
2025/03/22 17:51:36.068 15630 15690 Debug Unity [4.0 KB-8.0 KB]: 310 frames
2025/03/22 17:51:36.068 15630 15690 Debug Unity 
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Requested Block Size 2.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Block count 1
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated memory 4.7 KB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Large allocation bytes 0 B
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_TYPETREE_THREAD]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak usage frame count: 
2025/03/22 17:51:36.068 15630 15690 Debug Unity [0-1.0 KB]: 310 frames
2025/03/22 17:51:36.068 15630 15690 Debug Unity 
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Requested Block Size 2.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Block count 0
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Allocated memory 0 B
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Peak Large allocation bytes 0 B
2025/03/22 17:51:36.068 15630 15690 Debug Unity [ALLOC_PROFILER]
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Peak usage frame count: 
2025/03/22 17:51:36.068 15630 15690 Debug Unity [256.0 KB-0.5 MB]: 309 frames
2025/03/22 17:51:36.068 15630 15690 Debug Unity , [32.0 MB-64.0 MB]: 1 frames
2025/03/22 17:51:36.068 15630 15690 Debug Unity 
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Requested Block Size 16.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Peak Block count 3
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Peak Allocated memory 33.3 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity   Peak Large allocation bytes 0 B
2025/03/22 17:51:36.068 15630 15690 Debug Unity     [ALLOC_PROFILER_BUCKET]
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Large Block size 4.0 MB
2025/03/22 17:51:36.068 15630 15690 Debug Unity       Used Block count 1
2025/03/22 17:51:36.073 15630 15630 Warn FlutterEmbedLog onDetachedFromActivity - this means the Flutter activity for your app was destroyed. This scenario is not supported
2025/03/22 17:51:36.074 15630 15630 Debug FlutterEmbedLog onDetachedFromEngine
2025/03/22 17:51:36.075 15630 15630 Debug Unity PersistentUnitySurface.preserveContent: com.unity3d.player.a{9eafb41 VFE...... ........ 0,0-1440,2015 #7f07005b app:id/unitySurfaceView}
2025/03/22 17:51:36.075 15630 15630 Debug Unity PersistentUnitySurface.PlaceholderView.Copy: com.unity3d.player.a{9eafb41 VFE...... ........ 0,0-1440,2015 #7f07005b app:id/unitySurfaceView} Width 1440 Height 2015
2025/03/22 17:51:36.075 15630 15652 Warn OpenGLRenderer Surface doesn't have any previously queued frames, nothing to readback from
2025/03/22 17:51:36.076 15630 15630 Debug FlutterEmbedLog UnityPlayerSingleton onWindowVisibilityChanged 8
2025/03/22 17:51:36.076 15630 15630 Debug FlutterEmbedLog UnityPlatformView dispose
2025/03/22 17:51:36.076 15630 15630 Info FlutterEmbedLog Detached Unity from view
2025/03/22 17:51:36.076 15630 15630 Info FlutterEmbedLog No more EmbedUnity views in stack, pausing Unity
2025/03/22 17:51:36.076 15630 15630 Warn WindowOnBackDispatcher sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda19@6e0f8e6
2025/03/22 17:51:36.077 15630 15630 Debug InputMethodManager correctSkyLinkDisplayId context 16 -> 0 android.window.WindowContext@582a7c5
2025/03/22 17:51:36.085 15630 15630 Debug InputMethodManager correctSkyLinkDisplayId context 16 -> 0 android.window.WindowContext@582a7c5
2025/03/22 17:51:36.089 15630 15697 Info BpBinder onLastStrongRef automatically unlinking death recipients: 
2025/03/22 17:51:36.116 15630 15630 Warn WindowOnBackDispatcher sendCancelIfRunning: isInProgress=falsecallback=android.view.ViewRootImpl$$ExternalSyntheticLambda19@4daaa0c
2025/03/22 17:51:36.125 15630 15630 Debug Unity onPixelCopyFinished: 3
```
</details>

<details>
<summary>Log when launching example application for the second time</summary>

```
0001/01/01 00:00:00.000 -1 -1 Info  --------- beginning of system
2025/03/22 17:51:59.501 15630 15647 Debug ResumeActivityItem App resume preExecute
0001/01/01 00:00:00.000 -1 -1 Info  --------- beginning of main
2025/03/22 17:51:59.514 15630 15630 Info AdrenoVK-0 QUALCOMM build          : 56a1d551e1, I4cd85de53f
2025/03/22 17:51:59.514 15630 15630 Info AdrenoVK-0 Build Date              : 06/21/24
2025/03/22 17:51:59.514 15630 15630 Info AdrenoVK-0 Shader Compiler Version : E031.45.02.15
2025/03/22 17:51:59.514 15630 15630 Info AdrenoVK-0 Local Branch            : 
2025/03/22 17:51:59.514 15630 15630 Info AdrenoVK-0 Remote Branch           : refs/tags/AU_LINUX_ANDROID_LA.VENDOR.14.3.0.11.00.00.973.576
2025/03/22 17:51:59.514 15630 15630 Info AdrenoVK-0 Remote Branch           : NONE
2025/03/22 17:51:59.514 15630 15630 Info AdrenoVK-0 Reconstruct Branch      : NOTHING
2025/03/22 17:51:59.514 15630 15630 Info AdrenoVK-0 Build Config            : S P 16.1.2 AArch64
2025/03/22 17:51:59.514 15630 15630 Info AdrenoVK-0 Driver Path             : /vendor/lib64/hw/vulkan.adreno.so
2025/03/22 17:51:59.514 15630 15630 Info AdrenoVK-0 Driver Version          : 0762.23
2025/03/22 17:51:59.514 15630 15630 Info AdrenoVK-0 PFP                     : 0x01520175
2025/03/22 17:51:59.514 15630 15630 Info AdrenoVK-0 ME                      : 0x01520023
2025/03/22 17:51:59.514 15630 15630 Info AdrenoVK-0 Application Name    : Impeller
2025/03/22 17:51:59.514 15630 15630 Info AdrenoVK-0 Application Version : 0x00400000
2025/03/22 17:51:59.514 15630 15630 Info AdrenoVK-0 Engine Name         : Impeller
2025/03/22 17:51:59.514 15630 15630 Info AdrenoVK-0 Engine Version      : 0x00400000
2025/03/22 17:51:59.514 15630 15630 Info AdrenoVK-0 Api Version         : 0x00401000
2025/03/22 17:51:59.516 15630 15630 Info flutter [IMPORTANT:flutter/shell/platform/android/android_context_vk_impeller.cc(60)] Using the Impeller rendering backend (Vulkan).
2025/03/22 17:51:59.535 15630 15630 Debug FlutterEmbedLog onAttachedToEngine
2025/03/22 17:51:59.536 15630 15630 Debug FlutterEmbedLog onAttachedToActivity
2025/03/22 17:51:59.546 15630 15630 Verbose ActivityThread Performing resume of ActivityRecord{852b052 token=android.os.BinderProxy@b93b031 {com.learntoflutter.flutter_embed_unity_android_example/com.learntoflutter.flutter_embed_unity_android_example.MainActivity}} finished=false
2025/03/22 17:51:59.546 15630 15630 Debug perfmonitor resume={com.learntoflutter.flutter_embed_unity_android_example/com.learntoflutter.flutter_embed_unity_android_example.MainActivity} state=2
2025/03/22 17:51:59.546 15630 15630 Debug FlutterEmbedLog Activity resumed, resuming Unity
2025/03/22 17:51:59.569 15630 15944 Warn qdgralloc GetSize: Pixel format: 0x3b is not supported by gralloc
2025/03/22 17:51:59.569 15630 15944 Warn qdgralloc gralloc failed to allocate buffer for size 0 format 59 AWxAH 1x1 usage 2816
2025/03/22 17:51:59.569 15630 15944 Error Gralloc4 isSupported(1, 1, 59, 1, ...) failed with 7
2025/03/22 17:51:59.569 15630 15944 Error GraphicBufferAllocator Failed to allocate (4 x 4) layerCount 1 format 59 usage b00: 2
2025/03/22 17:51:59.569 15630 15944 Error AHardwareBuffer GraphicBuffer(w=4, h=4, lc=1) failed (Unknown error -2), handle=0x0
2025/03/22 17:51:59.569 15630 15944 Warn qdgralloc GetSize: Pixel format: 0x3b is not supported by gralloc
2025/03/22 17:51:59.569 15630 15944 Warn qdgralloc gralloc failed to allocate buffer for size 0 format 59 AWxAH 1x1 usage 2816
2025/03/22 17:51:59.569 15630 15944 Error Gralloc4 isSupported(1, 1, 59, 1, ...) failed with 7
2025/03/22 17:51:59.569 15630 15944 Error GraphicBufferAllocator Failed to allocate (4 x 4) layerCount 1 format 59 usage b00: 2
2025/03/22 17:51:59.569 15630 15944 Error AHardwareBuffer GraphicBuffer(w=4, h=4, lc=1) failed (Unknown error -2), handle=0x0
2025/03/22 17:52:00.113 15630 15630 Debug com.learntoflutter.flutter_embed_unity_android.platformView.UnityViewFactory@1f66f9b UnityViewFactory creating view 0
2025/03/22 17:52:00.113 15630 15630 Info FlutterEmbedLog Attached Unity to view
2025/03/22 17:52:00.113 15630 15630 Info Unity windowFocusChanged: true
=======>>>>> Crashing-like behavior occurs here <<<<<=======
```
</details>

**Comment by jamesncl** [comment]
Thanks for the bug report. I can reproduce it on Samsung S22, Android 14.

If you look at [`FlutterEmbedUnityAndroidPlugin.kt`](https://github.com/learntoflutter/flutter_embed_unity/blob/416035cc1af2784f13e9df28e2e0b52820cbe686/flutter_embed_unity_2022_3_android/android/src/main/kotlin/com/learntoflutter/flutter_embed_unity_android/FlutterEmbedUnityAndroidPlugin.kt#L118), we use [`ActivityAware`](https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/activity/ActivityAware.html) callbacks to detect when the android activity lifecycle changes. It looks like when you exit the app using the back button, `onDetachedFromActivity` is called. I think you're right in suspecting that this is because the activity has been destroyed.

Unfortunately, I never figured out how to solve this problem. I can't remember the exact details, but I think Unity detects when the activity is destroyed, and assumes the entire app has been killed. In normal circumstances this is the right thing to do - embedding Unity inside a Flutter application is fundamentally a bit of a hack, which is why this is kind of a difficult problem to solve.

I did spend some time playing around with overriding the UnityPlayer kill function in [`UnityPlayerSingleton.kt`](https://github.com/learntoflutter/flutter_embed_unity/blob/416035cc1af2784f13e9df28e2e0b52820cbe686/flutter_embed_unity_2022_3_android/android/src/main/kotlin/com/learntoflutter/flutter_embed_unity_android/unity/UnityPlayerSingleton.kt#L122), but when bringing the app back into the foreground I just ran into a different error (PlayAssetDeliveryUnityWrapper.init() should be called only once). But at some point I gave up.

So it may be possible to fix this, but I don't know how. Feel free to play around with the code if you're feeling adventurous (there's some [info on contributing in the wiki](https://github.com/learntoflutter/flutter_embed_unity/wiki)).

Strangely, I can't reproduce the problem in the only app I develop where I use flutter_embed_unity - you can exit the app using the back button, then reopen the app, and it doesn't crash when the Unity page is reopened. I don't know why, the configuration as far as I can see is the same (although I'm not using AR - but I just tried ripping AR out of the example project, and this doesn't seem to make any difference).

**Comment by RF103T** [comment]
> Thanks for the bug report. I can reproduce it on Samsung S22, Android 14.
> 
> If you look at [`FlutterEmbedUnityAndroidPlugin.kt`](https://github.com/learntoflutter/flutter_embed_unity/blob/416035cc1af2784f13e9df28e2e0b52820cbe686/flutter_embed_unity_2022_3_android/android/src/main/kotlin/com/learntoflutter/flutter_embed_unity_android/FlutterEmbedUnityAndroidPlugin.kt#L118), we use [`ActivityAware`](https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/activity/ActivityAware.html) callbacks to detect when the android activity lifecycle changes. It looks like when you exit the app using the back button, `onDetachedFromActivity` is called. I think you're right in suspecting that this is because the activity has been destroyed.
> 
> Unfortunately, I never figured out how to solve this problem. I can't remember the exact details, but I think Unity detects when the activity is destroyed, and assumes the entire app has been killed. In normal circumstances this is the right thing to do - embedding Unity inside a Flutter application is fundamentally a bit of a hack, which is why this is kind of a difficult problem to solve.
> 
> I did spend some time playing around with overriding the UnityPlayer kill function in [`UnityPlayerSingleton.kt`](https://github.com/learntoflutter/flutter_embed_unity/blob/416035cc1af2784f13e9df28e2e0b52820cbe686/flutter_embed_unity_2022_3_android/android/src/main/kotlin/com/learntoflutter/flutter_embed_unity_android/unity/UnityPlayerSingleton.kt#L122), but when bringing the app back into the foreground I just ran into a different error (PlayAssetDeliveryUnityWrapper.init() should be called only once). But at some point I gave up.
> 
> So it may be possible to fix this, but I don't know how. Feel free to play around with the code if you're feeling adventurous (there's some [info on contributing in the wiki](https://github.com/learntoflutter/flutter_embed_unity/wiki)).
> 
> Strangely, I can't reproduce the problem in the only app I develop where I use flutter_embed_unity - you can exit the app using the back button, then reopen the app, and it doesn't crash when the Unity page is reopened. I don't know why, the configuration as far as I can see is the same (although I'm not using AR - but I just tried ripping AR out of the example project, and this doesn't seem to make any difference).

This issue is affecting the user experience a little bit and I would like to try to solve it. Can you provide any more infomation about "`the only app I develop where I use flutter_embed_unity`"?

Another strange thing is that exiting with the back button doesn't seem to exit the process, debugging doesn't end in this case either. But I've tried multiple ways in flutter (pretty much just calling `SystemNavigator.pop` from anywhere possible) and I can't exit the app completely.

**Comment by RF103T** [comment]
> Thanks for the bug report. I can reproduce it on Samsung S22, Android 14.
> 
> If you look at [`FlutterEmbedUnityAndroidPlugin.kt`](https://github.com/learntoflutter/flutter_embed_unity/blob/416035cc1af2784f13e9df28e2e0b52820cbe686/flutter_embed_unity_2022_3_android/android/src/main/kotlin/com/learntoflutter/flutter_embed_unity_android/FlutterEmbedUnityAndroidPlugin.kt#L118), we use [`ActivityAware`](https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/activity/ActivityAware.html) callbacks to detect when the android activity lifecycle changes. It looks like when you exit the app using the back button, `onDetachedFromActivity` is called. I think you're right in suspecting that this is because the activity has been destroyed.
> 
> Unfortunately, I never figured out how to solve this problem. I can't remember the exact details, but I think Unity detects when the activity is destroyed, and assumes the entire app has been killed. In normal circumstances this is the right thing to do - embedding Unity inside a Flutter application is fundamentally a bit of a hack, which is why this is kind of a difficult problem to solve.
> 
> I did spend some time playing around with overriding the UnityPlayer kill function in [`UnityPlayerSingleton.kt`](https://github.com/learntoflutter/flutter_embed_unity/blob/416035cc1af2784f13e9df28e2e0b52820cbe686/flutter_embed_unity_2022_3_android/android/src/main/kotlin/com/learntoflutter/flutter_embed_unity_android/unity/UnityPlayerSingleton.kt#L122), but when bringing the app back into the foreground I just ran into a different error (PlayAssetDeliveryUnityWrapper.init() should be called only once). But at some point I gave up.
> 
> So it may be possible to fix this, but I don't know how. Feel free to play around with the code if you're feeling adventurous (there's some [info on contributing in the wiki](https://github.com/learntoflutter/flutter_embed_unity/wiki)).
> 
> Strangely, I can't reproduce the problem in the only app I develop where I use flutter_embed_unity - you can exit the app using the back button, then reopen the app, and it doesn't crash when the Unity page is reopened. I don't know why, the configuration as far as I can see is the same (although I'm not using AR - but I just tried ripping AR out of the example project, and this doesn't seem to make any difference).

#### *I accidentally clicked to close the issue and now reopened it.*

This issue is affecting the user experience a little bit and I would like to try to solve it. Can you provide any more infomation about "the only app I develop where I use flutter_embed_unity"?

Another strange thing is that exiting with the back button doesn't seem to exit the process, debugging doesn't end in this case either. But I've tried multiple ways in flutter (pretty much just calling SystemNavigator.pop from anywhere possible) and still can't exit the app completely.

**Comment by timbotimbo** [comment]
Just did some quick testing, without diving into the plugin itself.



It crashed on all 3 my devices:
- Samsung S8 Android 9  
- Samsung S20FE Android 13  
- Samsung S25U Android 15  

I got it to crash using all 3 tested Flutter versions:  
- 3.24.5 
- 3.27.1
- 3.29.2  

##
My exact steps  
- Launch the example app from VS code
- Exit the app using back button. (not gesture in my case)
- Click the app on homescreen
- App crashes during boot
  
Exit using home button does not lead to a crash when opening the app.

Screen recoring on S20FE, Android 13:

https://github.com/user-attachments/assets/616d6a54-c9b1-4b29-82ff-7c402591501b

##
Some of the things I tried:  

- Building Unity with only an empty scene (to avoid AR)
- Running with `flutter run --release` 
- Building a release apk and installing it.
- Disabling predictive back using `android:enableOnBackInvokedCallback="false"`
- Disabling impeller in Flutter
- Use FlutterActivity instead of FakeUnityPlayerActivity
- Use FlutterFragmentActivity instead of FakeUnityPlayerActivity


##
When using FlutterFragmentActivity, it only crashes the first time. Any relaunches after the crash won't show the same issue.

**Comment by jamesncl** [comment]
> This issue is affecting the user experience a little bit and I would like to try to solve it. Can you provide any more infomation about "the only app I develop where I use flutter_embed_unity"?

> When using FlutterFragmentActivity, it only crashes the first time. Any relaunches after the crash won't show the same issue.

I can confirm this. Using FlutterFragmentActivity does indeed mean that the crash only happens once:

**MainActivity.kt**
```kotlin
package com.learntoflutter.flutter_embed_unity_example

import com.learntoflutter.flutter_embed_unity_android.unity.IFakeUnityPlayerActivity
import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity: FlutterFragmentActivity(), IFakeUnityPlayerActivity {

    // ------------------------------------------------
    // This is to work around issue with UnityPlayer and AR
    // See comments on IFakeUnityPlayerActivity
    var mUnityPlayer: Any? = null
    override fun setmUnityPlayer(mUnityPlayer: Any?) {
        this.mUnityPlayer = mUnityPlayer
    }
    // ------------------------------------------------
}
```


The app where I use this package also uses FlutterFragmentActivity, which I guess is why I've never even noticed this bug before.

**Comment by jamesncl** [comment]
These seem to be related issues from [flutter_unity_widget](https://pub.dev/packages/flutter_unity_widget):

[Closing unity screen and relaunching it crashes the app #46](https://github.com/juicycleff/flutter-unity-view-widget/issues/46#top)

[Android app crashes on returning to Unity screen #323](https://github.com/juicycleff/flutter-unity-view-widget/issues/323#top)

**Comment by timbotimbo** [comment]
Those flutter_unity_widget issues are quite old.  
I just checked the example on Flutter 3.24.5 and could not reproduce the crash.

Maybe because that widget isn't persistent it gets disposed better?

**Comment by jamesncl** [comment]
> I just checked the example on Flutter 3.24.5 and could not reproduce the crash.

Hmm that's interesting, I thought you had already tried 3.24.5 and it did crash - did you definitely uninstall the app before trying again on 3.24.5? I would try it myself but my home internet has gone down, so I'm trying not to do big downloads which will kill my mobile data usage!

> Maybe because that widget isn't persistent it gets disposed better?

Do you mean FlutterFragmentActivity? I was wondering what the difference was between a standard Activity and a Fragment Activity. I've (thank god) never had to learn much about how android activities actually work.

**Comment by timbotimbo** [comment]
I meant the other flutter_unity_widget plugin you linked.  

I tried that example with 3.24.5 (which crashes here) and haven't managed to trigger the crash yet.
That plugin doesn't persist any controller when the widget is removed. (Although unity keeps its state)

Might indicate that it is more likely to be in plugin code than a Unity limitation.

**Comment by jamesncl** [comment]
Ah right I see what you mean, thanks for clarifying. So basically this should be solvable. I'll have a look at how flutter_unity_widget handles it (although I find the code in that plugin very hard to follow - one of the main reasons I created flutter_embed_unity in the first place) and see if we can use the same logic here in flutter_embed_unity.

**Comment by jamesncl** [comment]
> I meant the other flutter_unity_widget plugin you linked.
> 
> I tried that example with 3.24.5 (which crashes here) and haven't managed to trigger the crash yet.

And sorry, just to clarify again, do you know if flutter_unity_widget crashes with 3.27 or later? Or is it just 3.24.5 where it doesn't crash

**Comment by jamesncl** [comment]
This may be a solution. Simply calling `unload()` in `FlutterEmbedUnityAndroidPlugin.kt` on the UnityPlayer instance when the activity is detached from the plugin appears to prevent crashing when re-opening.

```diff
class FlutterEmbedUnityAndroidPlugin : FlutterPlugin, ActivityAware {
 
     // ActivityAware
     override fun onDetachedFromActivity() {
-        Log.w(logTag, "onDetachedFromActivity - this means the Flutter activity " +
-                    "for your app was destroyed. This scenario is not supported")
-        // TODO(Is there any way to handle FlutterActivity onDestroy()?)
+        Log.i(logTag, "onDetachedFromActivity - the Flutter activity has been detached, unloading unity")
+        UnityPlayerSingleton.getInstance()?.unload()
         UnityPlayerSingleton.flutterActivity = null
```

So far I've only tried this on my Samsung S22 in debug mode.

**Comment by jamesncl** [comment]
`unload()` also seems to work with both `FlutterActivity` and `FlutterFragmentActivity`

**Comment by jamesncl** [comment]
I've published a new prerelease version which unloads unity:

```yaml
dependencies:
  flutter_embed_unity: ^1.2.6-beta.1
```

I've just tried this on my own app, and strangely it does not seem to have fixed the problem. But it seems to have fixed it in the example. I'm not sure why. I suspect it may be because I used an older version of Unity 2022.3 for my app.

I'd be very grateful if you could both try 1.2.6-beta.1 and let me know if it fixes the problem for you.

**Comment by RF103T** [comment]
> I've published a new prerelease version which unloads unity:
> 
> dependencies:
>   flutter_embed_unity: ^1.2.6-beta.1
> I've just tried this on my own app, and strangely it does not seem to have fixed the problem. But it seems to have fixed it in the example. I'm not sure why.
> 
> I'd be very grateful if you could both try 1.2.6-beta.1 and let me know if it fixes the problem for you.

I tested it on my device and the problem is fixed. After using the back button, the process exits normally and debugging ends at the same time.

```
...
D/Unity   (32432):     [ALLOC_PROFILER_BUCKET]
D/Unity   (32432):       Large Block size 4.0 MB
D/Unity   (32432):       Used Block count 1
I/FlutterEmbedLog(32432): onDetachedFromActivity - the Flutter activity has been detached, unloading unity
Lost connection to device.

Exited.
```

**Comment by timbotimbo** [comment]
@jamesncl 
> And sorry, just to clarify again, do you know if flutter_unity_widget crashes with 3.27 or later? Or is it just 3.24.5 where it doesn't crash

I only tried 3.24.5 this time because Flutter version differences don't seem to change this behaviour.

##
> I'd be very grateful if you could both try 1.2.6-beta.1 and let me know if it fixes the problem for you.

Running the example unedited like [in my first screen capture](https://github.com/learntoflutter/flutter_embed_unity/issues/39#issuecomment-2754042440) and it does not crash anymore.

Running the example without the first Unity widget like [my second screen capture](https://github.com/learntoflutter/flutter_embed_unity/issues/39#issuecomment-2754055683) and it crashes again.

##

**To Reproduce**

Remove the main `EmbedUnity` widget in the example,.
```diff
return Column(
                children: [
                  Expanded(
-                    child: EmbedUnity(
-                      onMessageFromUnity: (String data) {
-                        // A message has been received from a Unity script
-                        if (data == "touch") {
-                          setState(() {
-                            _numberOfTaps += 1;
-                          });
-                        } else if (data == "scene_loaded") {
-                          _sendRotationSpeedToUnity(_rotationSpeed);
-                        } else if (data == "ar:true") {
-                          setState(() {
-                            _isUnityArSupportedOnDevice = true;
-                          });
-                        } else if (data == "ar:false") {
-                          setState(() {
-                            _isUnityArSupportedOnDevice = false;
-                          });
-                        }
-                      },
-                    ),
+                   child: const SizedBox(),
                  ),
                  Padding(
                    padding: const EdgeInsets.all(16),
                    child: Text(
                      "Flutter logo has been touched $_numberOfTaps times",

```
1. Launch the example and start Unity with "Open route 2". 
2. Now back button/gesture twice to leave the app.
3. Relaunch the app and click "Open route 2".
4. It crashes again.

**However** if you edit this, it won't crash anymore.  
This removes the back action between the initial screen and route2.
```diff
- Navigator.push(
+ Navigator.pushReplacement(
	context,
	MaterialPageRoute(
		builder: (context) => const Route2()),
);
```
So with your fix it now seems to depend on whether Unity is currently on the page when the app is disposed.
If Unity is not in the page when the app is disposed, the crash still happens.

**Comment by jamesncl** [comment]
> So with your fix it now seems to depend on whether Unity is currently on the page when the app is disposed.
> If Unity is not in the page when the app is disposed, the crash still happens.

Yep, it seems you're absolutely right, thank you. This is the case for my app where it still crashes - Unity is shown quite far down in the page stack.

So, when navigating back from a screen with unity to a screen without unity, UnityPlayer is paused; when exiting the app from a screen with Unity, I don't think unity is paused before it is unloaded. I wonder if that is the key difference. I'll do some more experimenting.

**Comment by jamesncl** [comment]
Calling `destroy()` instead of `unload()` on the UnityPlayer when the activity is detached from the plugin appears to improve things.

In both scenarios (when Unity is currently on the page when the app is disposed, and when it's not) using the example project, the app doesn't crash when re-opening.

However I'm a bit worried that calling `destroy()` on Unity may have some unintended side effects. In my app, if I go to a screen with Unity, then navigate back until the app exits, Android Studio loses connection ("Lost connection to device - Dart compliler exited"), which it didn't do before. Strangely, if I open my app, but don't open Unity, then navigate back to exit, then go back in and open Unity, then navigate back to exit again, Android Studio doesn't lose connection. I don't think this is a huge problem but it's concerning that I don't know exactly what's happening here.

I've published a new prerelease 1.2.6-beta.2, it would be great if you could test this in your own apps (@RF103T you will want to make sure this new version does not regress the fix in your project), and let me know if there are any problems: 

```yaml
dependencies:
  flutter_embed_unity: ^1.2.6-beta.2
```

**Comment by RF103T** [comment]
> I've published a new prerelease 1.2.6-beta.2, it would be great if you could test this in your own apps ([@RF103T](https://github.com/RF103T) you will want to make sure this new version does not regress the fix in your project), and let me know if there are any problems:

The new version works well too. I'll keep testing it for a while to see if there are any other issues.

**Comment by timbotimbo** [comment]
The latest one doesn't crash on both my test cases above.

I can confirm the Flutter debugger getting killed op app exit,  using Visual Studio Code.

The flutter_unity_widget example also shows that behaviour for me.

I don't use this plugin in any production apps yet, i'm just helping out to have this plugin as a viable fallback for my existing flutter+unity projects.
